from .AdminMenu import AdminMenu
from .CourseAction import CourseAction
from .CourseMenu import CourseMenu
from .CreateCourse import CreateCourse
from .CreateStudent import CreateStudent
from .SplashScreen import SplashScreen
from .StudentAction import StudentAction
from .StudentMenu import StudentMenu
from .TimetableMenu import TimetableMenu
from .UpdateCourse import UpdateCourse
from .UpdateStudent import UpdateStudent
